- name: train
  help: "Train the pipeline"
  script:
    - "python -m spacy train config.cfg -o training/ \
      --paths.train ../data/train.spacy" --paths.dev ../dev.spacy"
  deps:
    - "../data/train.spacy"
    - "../data/dev.spacy"
    - "config.cfg"
  outputs:
    - "training/model-best"